# Generated by Django 4.1.1 on 2022-09-23 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProveedores', models.CharField(help_text='Ingrese el Codigo del Proveedor', max_length=100)),
                ('nombreProveedores', models.CharField(help_text='Ingrese el Nombre del Proveedor', max_length=100)),
                ('apellidoProveedores', models.CharField(help_text='Ingrese el Apellido del Proveedor', max_length=100)),
                ('direccionProveedores', models.CharField(help_text='Ingrese la Direccion del Proveedor', max_length=100)),
                ('telefonoProveedores', models.CharField(help_text='Ingrese el Telefono del Proveedor', max_length=12)),
                ('provinviaProveedores', models.CharField(help_text='Ingrese la Provinvia del Proveedor', max_length=100)),
            ],
            options={
                'verbose_name': 'Proveedores',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Distribuir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_productos', models.IntegerField(verbose_name='cantidad de productos')),
                ('codigoproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('codigoproveedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores')),
            ],
            options={
                'verbose_name': 'Cantidad de distribucion',
                'verbose_name_plural': 'Cantidad de distribuciones',
            },
        ),
    ]
