# Generated by Django 4.1.1 on 2022-09-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.CharField(help_text='Ingrese el Codigo del Producto', max_length=100)),
                ('descripcion', models.CharField(max_length=500, verbose_name='descripcion del producto')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('numeroEsxistencias', models.IntegerField(verbose_name='numero de existencias')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': ' productos',
            },
        ),
    ]
